@startuml

Tracker -> Api: create payment
Api -> Paypal: payment
Paypal -> Api: return approval URL
Api > Tracker: return success
Tracker -> Api: get redirect URL
Api -> Tracker: return redirect URL
Tracker -> Paypal: redirect to payment page
Paypal -> Tracker: redirect to return URL
Tracker -> Api: confirm payment
Api -> Paypal: execute payment
Paypal -> Api: return success
Api -> Api: store transaction id for eventual refund
Api -> Tracker: success

@enduml
