@startuml

[API] as api
[Webapp] as webapp
[Issue Tracker\nPlugin] as plugin
[Payment Processor] as payments

plugin -> api
webapp -> api
webapp -> payments

note right of plugin : Should be thin, becomes thick

@enduml
