@startuml

Tracker -> Api: Confirm Payment
Api -> Paypal: PreapprovalRequest
Paypal -> Api: Return preapprovalKey
Api -> Tracker: Redirect URL
Tracker -> Paypal: Redirect to payment page
Paypal -> Tracker: Redirect to return URL
Tracker -> Api: Mark as success
Api -> Paypal: Validate payment via PreapprovalDetails
Paypal -> Api: Return valid payment
Api -> Api: Store preapproval key
Api -> Tracker: Success

@enduml
